#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('SHADERAPIDX9', True)
	conf.define('SHADER_DLL_EXPORT', True)

def build(bld):
	libs = ['tier0', 'bitmap', 'tier1', 'tier2', 'interfaces', 'vstdlib', 'videocfg', 'mathlib', 'd3d9', 'd3dx', 'shaderlib', 'vtf', 'appframework', 'bzip2', 'SDL2']

	includes = ['..']

	source = [
		'colorformatdx8.cpp',
		'd3d_async.cpp',								
		'../../public/filesystem_helpers.cpp',
		'hardwareconfig.cpp',
		'meshbase.cpp',
		'meshdx8.cpp',
		'shaderapidx8.cpp',
		'shaderdevicebase.cpp',
		'shaderapibase.cpp',
		'shaderdevicedx8.cpp',
		'shadershadowdx8.cpp',
		'texturedx8.cpp',
		'TransitionTable.cpp',
		'cvballoctracker.cpp',
		'vertexdecl.cpp',
		'vertexshaderdx8.cpp',
		'../../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS != 'win32':
		source += ['winutils.cpp']

	bld.shlib(
		source   = source,
		target   = 'shaderapidx9',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
