#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = ['../thirdparty/protobuf-2.6.1/src']

	source = [
		'base_gcmessages.pb.cc',
		'cstrike15_gcmessages.pb.cc',
		'cstrike15_usermessages.pb.cc',
		'engine_gcmessages.pb.cc',
		'gcsdk_gcmessages.pb.cc',
		'gcsystemmsgs.pb.cc',
		'netmessages.pb.cc',
		'network_connection.pb.cc',
		'steammessages.pb.cc'
	]

	bld.stlib(
		source   = source,
		target   = 'generated_proto',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
