#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('SERVERBROWSER_EXPORTS', True)

def build(bld):
	libs = ['tier0', 'vgui_controls', 'dmxloader', 'tier1', 'tier2', 'tier3', 'interfaces', 'vstdlib', 'mathlib']

	includes = []

	source = [
		'BaseGamesPage.cpp',
		'blacklistedservers.cpp',
		'CustomGames.cpp',
		'DialogAddServer.cpp',
		'DialogGameInfo.cpp',
		'DialogServerPassword.cpp',
		'FavoriteGames.cpp',
		'FriendsGames.cpp',
		'HistoryGames.cpp',
		'InternetGames.cpp',
		'LanGames.cpp',
		'ModList.cpp',
		'ServerBrowser.cpp',
		'ServerBrowserDialog.cpp',
		'ServerContextMenu.cpp',
		'ServerListCompare.cpp',
		'SpectateGames.cpp',
		'VACBannedConnRefusedDialog.cpp',
		'quicklistpanel.cpp',
		'../public/vgui_controls/vgui_controls.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		source   = source,
		target   = 'serverbrowser',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
