#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('NO_STRING_T', True)

def build(bld):
	libs = ['tier0', 'tier1', 'tier2', 'interfaces', 'vstdlib', 'mathlib', 'SDL2']

	includes = []

	source = [
		'inputstacksystem.cpp',
		'inputsystem.cpp',
		'steamcontroller.cpp',
		'key_translation.cpp',
		'../common/platforminputdevice.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'joystick.cpp',
			'xcontroller.cpp'
		]
	else:
		source += [
			'joystick_linux.cpp'
		]

	bld.shlib(
		source   = source,
		target   = 'inputsystem',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
