#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('FILESYSTEM_STDIO_EXPORTS', True)

def build(bld):
	libs = ['tier0', 'tier1', 'tier2', 'interfaces', 'vstdlib', 'vpk']

	includes = []

	source = [
		'basefilesystem.cpp',
		'basefilesystemasync.cpp',
		'filetracker.cpp',
		'filesystemasync.cpp',
		'filesystem_stdio.cpp',
		'../public/kevvaluescompiler.cpp',
		'../public/zip_utils.cpp',
		'QueuedLoader.cpp',			
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS != 'win32':
		source += ['linux_support.cpp']

	bld.shlib(
		source   = source,
		target   = 'filesystem_stdio',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
