#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('MDLCACHE_DLL_EXPORT', True)

def build(bld):
	libs = ['tier0', 'tier1', 'tier2', 'tier3', 'interfaces', 'vstdlib', 'mathlib']

	includes = []

	source = [
		'datacache.cpp',
		'mdlcache.cpp',
		'mdlcombine.cpp',
		'vtfcombine.cpp',
		'resourceaccesscontrol.cpp',
		'precachesystem.cpp',
		'../public/studio.cpp',
		'../public/studio_virtualmodel.cpp',
		'../common/studiobyteswap.cpp',
		'../utils/common/datalinker.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		source   = source,
		target   = 'datacache',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
