#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('SOUNDEMITTERSYSTEM_EXPORTS', True)

def build(bld):
	libs = ['tier0', 'tier1', 'tier2', 'tier3', 'interfaces', 'vstdlib']

	includes = ['.']

	source = [
		'soundemittersystembase.cpp',
		'../public/SoundParametersInternal.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		source   = source,
		target   = 'soundemittersystem',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
