#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
		'assetpicker.cpp',
		'baseassetpicker.cpp',
		'colorpickerpanel.cpp',
		'curveeditorpanel.cpp',
		'gamefiletreeview.cpp',
		'manipulator.cpp',
		'matsyscontrols.cpp',
		'mdlpanel.cpp',
		'mdlpicker.cpp',
		'mdlsequencepicker.cpp',
		'particlepicker.cpp',
		'picker.cpp',
		'potterywheelpanel.cpp',
		'proceduraltexturepanel.cpp',
		'QCGenerator.cpp',
		'sequencepicker.cpp',
		'sheetsequencepanel.cpp',
		'tgapicker.cpp',
		'tgapreviewpanel.cpp',
		'vmtpicker.cpp',
		'vmtpreviewpanel.cpp',
		'vtfpicker.cpp',
		'vtfpreviewpanel.cpp',
		'vmtpanel.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'matsys_controls',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
