#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
			'device_null.cpp',
			'mix.cpp',
			'simple_filter.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'windows_audio.cpp',
			'device_dsound.cpp',
			'device_xaudio2.cpp'
		]
	else:
		source += ['device_sdl.cpp']

	bld.stlib(
		source   = source,
		target   = 'soundsystem_lowlevel',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
