#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('FAST_MATERIALVAR_ACCESS', True)

def build(bld):
	libs = []

	includes = ['..']

	source = [
		'BaseShader.cpp',
		'ShaderDLL.cpp',
		'shaderlib_cvar.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'shaderlib',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
