#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
		'AppSystemGroup.cpp',
		'../public/filesystem_init.cpp',
	]

	if bld.env.DEST_OS == 'win32':
		source += [
			'VguiMatSysApp.cpp',
			'matsysapp.cpp',
			'WinApp.cpp'
		]
	else:
		source += [
			'posixapp.cpp',
			'sdlmgr.cpp'
		]

	bld.stlib(
		source   = source,
		target   = 'appframework',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
