#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = ['vtf.cpp']

	if bld.env.DEST_OS == 'win32':
		source += ['s3tc_decode.cpp']

	bld.stlib(
		source   = source,
		target   = 'vtf',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
