#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('STUDIORENDER_EXPORTS', True)

def build(bld):
	libs = ['tier0', 'bitmap', 'tier1', 'tier2', 'tier3', 'interfaces', 'vstdlib', 'mathlib']

	includes = []

	source = [
		'studiorender.cpp',
		'studiorendercontext.cpp',
		'flexrenderdata.cpp',
		'r_studio.cpp',
		'r_studiodecal.cpp',
		'r_studiodraw.cpp',
		'r_studiodraw_computeflexedvertex.cpp',
		'r_studioflex.cpp',
		'r_studiosubd.cpp',
		'r_studiosubd_patches.cpp',
		'r_studiogettriangles.cpp',
		'r_studiolight.cpp',
		'../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		source   = source,
		target   = 'studiorender',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
