#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = [
		'../game/shared',
		'../utils/common'
	]

	source = [
		'../game/shared/choreoactor.cpp',
		'../game/shared/choreochannel.cpp',
		'../game/shared/choreoevent.cpp',
		'../game/shared/choreoscene.cpp',
		'../game/shared/sceneimage.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'choreoobjects',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
