#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
		'BitmapFont.cpp',
		'FontAmalgam.cpp',
		'fontmanager.cpp',
		'FontEffects.cpp',
		'fonttexturecache.cpp',
		'texturedictionary.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['Win32Font.cpp']
	else:
		source += ['linuxfont.cpp']

	bld.stlib(
		source   = source,
		target   = 'vgui_surfacelib',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
