#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
		'resourcedictionary.cpp',
		'resourcefile.cpp',
		'resourceintrospection.cpp',
		'resourcestream.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'resourcefile',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
