#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('TIER1_STATIC_LIB', True)

def build(bld):
	libs = []

	includes = []

	source = [
		'appinstance.cpp',
		'bitbuf.cpp',
		'newbitbuf.cpp',
		'byteswap.cpp',
		'characterset.cpp',
		'checksum_crc.cpp',
		'checksum_md5.cpp',
		'checksum_sha1.cpp',
		'circularbuffer.cpp',
		'commandbuffer.cpp',
		'convar.cpp',
		'datamanager.cpp',
		'diff.cpp',
		'exprevaluator.cpp',
		'generichash.cpp',
		'interface.cpp',
		'keyvalues.cpp',
		'keyvaluesjson.cpp',
		'kvpacker.cpp',
		'lzmaDecoder.cpp',
		'lzss.cpp',
		'mempool.cpp',
		'memstack.cpp',
		'NetAdr.cpp',
		'splitstring.cpp',
		'rangecheckedvar.cpp',
		'stringpool.cpp',
		'strtools.cpp',
		'strtools_unicode.cpp',
		'tier1.cpp',
		'tier1_logging.cpp',
		'timeutils.cpp',
		'uniqueid.cpp',
		'utlbuffer.cpp',
		'utlbufferutil.cpp',
		'utlsoacontainer.cpp',
		'utlstring.cpp',
		'utlstringtoken.cpp',
		'utlsymbol.cpp',
		'miniprofiler_hash.cpp',
		'sparsematrix.cpp',
		'memoverride_dummy.cpp'
	]

	if bld.env.DEST_OS != 'win32':
		source += ['qsort_s.cpp']

	bld.stlib(
		source   = source,
		target   = 'tier1',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
