#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = ['../utils/common']

	source = [
		'raytrace.cpp',
		'trace2.cpp',
		'trace3.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'raytrace',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
