#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
		'builtin_constraints.cpp',
		'builtin_initializers.cpp',
		'builtin_particle_emitters.cpp',
		'builtin_particle_forces.cpp',
		'addbuiltin_ops.cpp',
		'builtin_particle_ops.cpp',
		'builtin_particle_render_ops.cpp',
		'particle_snapshot.cpp',
		'particle_sort.cpp',
		'particles.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'particels',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
