#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	conf.define('VSTDLIB_DLL_EXPORT', True)

def build(bld):
	libs = ['tier0', 'tier1', 'interfaces']

	includes = []

	source = [
		'coroutine.cpp',
		'cvar.cpp',
		'jobthread.cpp',
		'keyvaluessystem.cpp',
		'random.cpp',
		'vcover.cpp',
		'eventsystem.cpp',
		'vstrtools.cpp',
		'vstdlib_strtools.cpp',
		'../public/tier0/memoverride.cpp'
	]

	if bld.env.DEST_OS == 'win32':
		source += ['processutils.cpp']
		if bld.env.ALLOW64:
			source += ['getstackptr64.masm']

	bld.shlib(
		source   = source,
		target   = 'vstdlib',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
