#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
 		'rrrlib.cpp',
		'response_types.cpp',
		'response_types_internal.cpp',
		'response_system.cpp',
		'rr_speechconcept.cpp',
		'rr_response.cpp',
		'criteriaset.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'responserules_runtime',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
