#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = ['tier0', 'tier1', 'interfaces', 'vstdlib', 'celt']

	includes = [
		'../frame_encoder',
		'../..',
		'../../audio/public',
		'../../../thirdparty/celt-v0.11.3/libcelt'
	]

	source = [
		'../frame_encoder/voice_codec_frame.cpp',
		'voiceencoder_celt.cpp',
		'../../../public/tier0/memoverride.cpp'
	]

	bld.shlib(
		source   = source,
		target   = 'vaudio_celt',
		features = 'cxx',
		includes = includes,
		use      = libs,
		install_path = bld.env.BINPATH,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
