#! /usr/bin/env python

def options(opt):
	return

def configure(conf):
	return

def build(bld):
	libs = []

	includes = []

	source = [
		'bone_setup.cpp',
		'bone_ik.cpp',
		'bone_utils.cpp',
		'bone_decode.cpp',
		'bone_constraints.cpp'
	]

	bld.stlib(
		source   = source,
		target   = 'bonesetup',
		features = 'cxx',
		includes = includes,
		use      = libs,
		subsystem = bld.env.MSVC_SUBSYSTEM,
		idx = bld.get_taskgen_count()
	)
